# Site settings
title: New Zealand
client:
  name: Tourism New Zealand
  link: "https://www.newzealand.com/uk/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  From glacier-cut fjords and piercing mountains to golden beaches and buzzing urban adventures, discover the finest getaways in New Zealand.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/new-zealand" # the subpath of your site, e.g. /blog/
img:     "/new-zealand/_assets/img"
css:     "/new-zealand/_assets/css"
js:      "/new-zealand/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed